DELETE FROM dbo.WishlistItems WHERE ProductId IN (SELECT ProductId FROM dbo.Products);

DELETE FROM dbo.CartItems WHERE ProductId IN (SELECT ProductId FROM dbo.Products);
DELETE FROM dbo.OrderItems WHERE ProductId IN (SELECT ProductId FROM dbo.Products);


DELETE FROM dbo.Products;

SET IDENTITY_INSERT dbo.Categories OFF;


INSERT INTO dbo.Products (Name, Description, Price, Subcategory, ImageUrl, Stock, SellerId, CategoryId, DateAdded, DiscountPercentage)
VALUES
('Audio 1', 'Descripción 1', 15.00, 'Audio', '/images/electronica/audio/audio_1.jpg', 30, 2, 3, GETDATE(), 10),
('Audio 2', 'Descripción 2', 20.00, 'Audio', '/images/electronica/audio/audio_2.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 3', 'Descripción 3', 15.00, 'Audio', '/images/electronica/audio/audio_3.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 4', 'Descripción 4', 20.00, 'Audio', '/images/electronica/audio/audio_4.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 5', 'Descripción 5', 15.00, 'Audio', '/images/electronica/audio/audio_5.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 6', 'Descripción 6', 20.00, 'Audio', '/images/electronica/audio/audio_6.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 7', 'Descripción 7', 15.00, 'Audio', '/images/electronica/audio/audio_7.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 8', 'Descripción 8', 20.00, 'Audio', '/images/electronica/audio/audio_8.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 9', 'Descripción 9', 15.00, 'Audio', '/images/electronica/audio/audio_9.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 10', 'Descripción 10', 20.00, 'Audio', '/images/electronica/audio/audio_10.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 11', 'Descripción 11', 15.00, 'Audio', '/images/electronica/audio/audio_11.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 12', 'Descripción 12', 20.00, 'Audio', '/images/electronica/audio/audio_12.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 13', 'Descripción 13', 15.00, 'Audio', '/images/electronica/audio/audio_13.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 14', 'Descripción 14', 20.00, 'Audio', '/images/electronica/audio/audio_14.jpg', 30, 2, 3, GETDATE(), NULL),
('Audio 15', 'Descripción 15', 15.00, 'Audio', '/images/electronica/audio/audio_15.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 1', 'Descripción 1', 450.00, 'Camarás', '/images/electronica/camaras/camara_1.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 2', 'Descripción 2', 450.00, 'Camarás', '/images/electronica/camaras/camara_2.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 3', 'Descripción 3', 340.00, 'Camarás', '/images/electronica/camaras/camara_3.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 4', 'Descripción 4', 340.00, 'Camarás', '/images/electronica/camaras/camara_4.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 5', 'Descripción 5', 340.00, 'Camarás', '/images/electronica/camaras/camara_5.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 6', 'Descripción 6', 450.00, 'Camarás', '/images/electronica/camaras/camara_6.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 7', 'Descripción 7', 450.00, 'Camarás', '/images/electronica/camaras/camara_7.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 8', 'Descripción 8', 450.00, 'Camarás', '/images/electronica/camaras/camara_8.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 9', 'Descripción 9', 340.00, 'Camarás', '/images/electronica/camaras/camara_9.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 10', 'Descripción 10', 340.00, 'Camarás', '/images/electronica/camaras/camara_10.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 11', 'Descripción 11', 450.00, 'Camarás', '/images/electronica/camaras/camara_11.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 12', 'Descripción 12', 340.00, 'Camarás', '/images/electronica/camaras/camara_12.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 13', 'Descripción 13', 450.00, 'Camarás', '/images/electronica/camaras/camara_13.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 14', 'Descripción 14', 450.00, 'Camarás', '/images/electronica/camaras/camara_14.jpg', 30, 2, 3, GETDATE(), NULL),
('Camara 15', 'Descripción 15', 340.00, 'Camarás', '/images/electronica/camaras/camara_15.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 1', 'Descripción 1', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_1.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 2', 'Descripción 2', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_2.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 3', 'Descripción 3', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_3.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 4', 'Descripción 4', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_4.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 5', 'Descripción 5', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_5.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 6', 'Descripción 6', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_6.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 7', 'Descripción 7', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_7.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 8', 'Descripción 8', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_8.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 9', 'Descripción 9', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_9.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 10', 'Descripción 10', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_10.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 11', 'Descripción 11', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_11.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 12', 'Descripción 12', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_12.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 13', 'Descripción 13', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_13.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 14', 'Descripción 14', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_14.jpg', 30, 2, 3, GETDATE(), NULL),
('Instrumento 15', 'Descripción 15', 140.00, 'Instrumentos musicales', '/images/electronica/instrumentos_musicales/instru_15.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 1', 'Descripción 1', 240.00, 'Móviles', '/images/electronica/moviles/movil_1.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 2', 'Descripción 2', 350.00, 'Móviles', '/images/electronica/moviles/movil_2.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 3', 'Descripción 3', 240.00, 'Móviles', '/images/electronica/moviles/movil_3.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 4', 'Descripción 4', 350.00, 'Móviles', '/images/electronica/moviles/movil_4.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 5', 'Descripción 5', 350.00, 'Móviles', '/images/electronica/moviles/movil_5.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 6', 'Descripción 6', 240.00, 'Móviles', '/images/electronica/moviles/movil_6.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 7', 'Descripción 7', 240.00, 'Móviles', '/images/electronica/moviles/movil_7.jpg', 30, 2, 3, GETDATE(), 16),
('Móvil 8', 'Descripción 8', 350.00, 'Móviles', '/images/electronica/moviles/movil_8.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 9', 'Descripción 9', 240.00, 'Móviles', '/images/electronica/moviles/movil_9.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 10', 'Descripción 10', 350.00, 'Móviles', '/images/electronica/moviles/movil_10.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 11', 'Descripción 11', 350.00, 'Móviles', '/images/electronica/moviles/movil_11.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 12', 'Descripción 12', 240.00, 'Móviles', '/images/electronica/moviles/movil_12.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 13', 'Descripción 13', 350.00, 'Móviles', '/images/electronica/moviles/movil_13.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 14', 'Descripción 14', 350.00, 'Móviles', '/images/electronica/moviles/movil_14.jpg', 30, 2, 3, GETDATE(), NULL),
('Móvil 15', 'Descripción 15', 240.00, 'Móviles', '/images/electronica/moviles/movil_15.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 1', 'Descripción 1', 600.00, 'TV', '/images/electronica/tv/tv_1.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 2', 'Descripción 2', 600.00, 'TV', '/images/electronica/tv/tv_2.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 3', 'Descripción 3', 430.00, 'TV', '/images/electronica/tv/tv_3.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 4', 'Descripción 4', 430.00, 'TV', '/images/electronica/tv/tv_4.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 5', 'Descripción 5', 430.00, 'TV', '/images/electronica/tv/tv_5.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 6', 'Descripción 6', 600.00, 'TV', '/images/electronica/tv/tv_6.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 7', 'Descripción 7', 430.00, 'TV', '/images/electronica/tv/tv_7.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 8', 'Descripción 8', 600.00, 'TV', '/images/electronica/tv/tv_8.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 9', 'Descripción 9', 430.00, 'TV', '/images/electronica/tv/tv_9.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 10', 'Descripción 10', 600.00, 'TV', '/images/electronica/tv/tv_10.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 11', 'Descripción 11', 430.00, 'TV', '/images/electronica/tv/tv_11.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 12', 'Descripción 12', 430.00, 'TV', '/images/electronica/tv/tv_12.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 13', 'Descripción 13', 600.00, 'TV', '/images/electronica/tv/tv_13.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 14', 'Descripción 14', 430.00, 'TV', '/images/electronica/tv/tv_14.jpg', 30, 2, 3, GETDATE(), NULL),
('TV 15', 'Descripción 15', 600.00, 'TV', '/images/electronica/tv/tv_15.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 1', 'Descripción 1', 55.00, 'Wi-fi', '/images/electronica/wifi/wifi_1.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 2', 'Descripción 2', 70.00, 'Wi-fi', '/images/electronica/wifi/wifi_2.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 3', 'Descripción 3', 55.00, 'Wi-fi', '/images/electronica/wifi/wifi_3.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 4', 'Descripción 4', 55.00, 'Wi-fi', '/images/electronica/wifi/wifi_4.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 5', 'Descripción 5', 70.00, 'Wi-fi', '/images/electronica/wifi/wifi_5.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 6', 'Descripción 6', 55.00, 'Wi-fi', '/images/electronica/wifi/wifi_6.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 7', 'Descripción 7', 70.00, 'Wi-fi', '/images/electronica/wifi/wifi_7.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 8', 'Descripción 8', 70.00, 'Wi-fi', '/images/electronica/wifi/wifi_8.jpg', 30, 2, 3, GETDATE(), 34),
('Router 9', 'Descripción 9', 55.00, 'Wi-fi', '/images/electronica/wifi/wifi_9.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 10', 'Descripción 10', 55.00, 'Wi-fi', '/images/electronica/wifi/wifi_10.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 11', 'Descripción 11', 70.00, 'Wi-fi', '/images/electronica/wifi/wifi_11.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 12', 'Descripción 12', 70.00, 'Wi-fi', '/images/electronica/wifi/wifi_12.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 13', 'Descripción 13', 55.00, 'Wi-fi', '/images/electronica/wifi/wifi_13.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 14', 'Descripción 14', 70.00, 'Wi-fi', '/images/electronica/wifi/wifi_14.jpg', 30, 2, 3, GETDATE(), NULL),
('Router 15', 'Descripción 15', 55.00, 'Wi-fi', '/images/electronica/wifi/wifi_15.jpg', 30, 2, 3, GETDATE(), NULL),
('Componente 1', 'Descripción 1', 30.00, 'Componentes', '/images/informatica/componentes/componente_1.jpg', 30, 2, 4, GETDATE(), NULL),
('Componente 2', 'Descripción 2', 30.00, 'Componentes', '/images/informatica/componentes/componente_2.jpg', 30, 2, 4, GETDATE(), NULL),
('Componente 3', 'Descripción 3', 30.00, 'Componentes', '/images/informatica/componentes/componente_3.jpg', 30, 2, 4, GETDATE(), NULL),
('Componente 4', 'Descripción 4', 30.00, 'Componentes', '/images/informatica/componentes/componente_4.jpg', 30, 2, 4, GETDATE(), NULL),
('Componente 5', 'Descripción 5', 30.00, 'Componentes', '/images/informatica/componentes/componente_5.jpg', 30, 2, 4, GETDATE(), NULL),
('Gaming 1', 'Descripción 1', 130.00, 'Gaming', '/images/informatica/gaming/gaming_1.jpg', 30, 2, 4, GETDATE(), NULL),
('Gaming 2', 'Descripción 2', 90.00, 'Gaming', '/images/informatica/gaming/gaming_2.jpg', 30, 2, 4, GETDATE(), NULL),
('Gaming 3', 'Descripción 3', 90.00, 'Gaming', '/images/informatica/gaming/gaming_3.jpg', 30, 2, 4, GETDATE(), NULL),
('Gaming 4', 'Descripción 4', 90.00, 'Gaming', '/images/informatica/gaming/gaming_4.jpg', 30, 2, 4, GETDATE(), NULL),
('Gaming 5', 'Descripción 5', 130.00, 'Gaming', '/images/informatica/gaming/gaming_5.jpg', 30, 2, 4, GETDATE(), NULL),
('Monitor 1', 'Descripción 1', 220.00, 'Monitores', '/images/informatica/monitores/monitor_1.jpg', 30, 2, 4, GETDATE(), NULL),
('Monitor 2', 'Descripción 2', 170.00, 'Monitores', '/images/informatica/monitores/monitor_2.jpg', 30, 2, 4, GETDATE(), NULL),
('Monitor 3', 'Descripción 3', 170.00, 'Monitores', '/images/informatica/monitores/monitor_3.jpg', 30, 2, 4, GETDATE(), NULL),
('Monitor 4', 'Descripción 4', 220.00, 'Monitores', '/images/informatica/monitores/monitor_4.jpg', 30, 2, 4, GETDATE(), NULL),
('Monitor 5', 'Descripción 5', 170.00, 'Monitores', '/images/informatica/monitores/monitor_5.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 1', 'Descripción 1', 650.00, 'Portátiles', '/images/informatica/portatiles/portatil_1.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 2', 'Descripción 2', 650.00, 'Portátiles', '/images/informatica/portatiles/portatil_2.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 3', 'Descripción 3', 650.00, 'Portátiles', '/images/informatica/portatiles/portatil_3.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 4', 'Descripción 4', 700.00, 'Portátiles', '/images/informatica/portatiles/portatil_4.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 5', 'Descripción 5', 650.00, 'Portátiles', '/images/informatica/portatiles/portatil_5.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 6', 'Descripción 6', 700.00, 'Portátiles', '/images/informatica/portatiles/portatil_6.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 7', 'Descripción 7', 650.00, 'Portátiles', '/images/informatica/portatiles/portatil_7.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 8', 'Descripción 8', 700.00, 'Portátiles', '/images/informatica/portatiles/portatil_8.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 9', 'Descripción 9', 700.00, 'Portátiles', '/images/informatica/portatiles/portatil_9.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 10', 'Descripción 10', 650.00, 'Portátiles', '/images/informatica/portatiles/portatil_10.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 11', 'Descripción 11', 700.00, 'Portátiles', '/images/informatica/portatiles/portatil_11.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 12', 'Descripción 12', 650.00, 'Portátiles', '/images/informatica/portatiles/portatil_12.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 13', 'Descripción 13', 700.00, 'Portátiles', '/images/informatica/portatiles/portatil_13.jpg', 30, 2, 4, GETDATE(), NULL),
('Portátil 14', 'Descripción 14', 600.00, 'Portátiles', '/images/informatica/portatiles/portatil_14.jpg', 30, 2, 4, GETDATE(), NULL),
('Sobremesa 1', 'Descripción 1', 930.00, 'Sobremesas', '/images/informatica/sobremesas/sobremesa_1.jpg', 30, 2, 4, GETDATE(), NULL),
('Sobremesa 2', 'Descripción 2', 870.00, 'Sobremesas', '/images/informatica/sobremesas/sobremesa_2.jpg', 30, 2, 4, GETDATE(), NULL),
('Sobremesa 3', 'Descripción 3', 930.00, 'Sobremesas', '/images/informatica/sobremesas/sobremesa_3.jpg', 30, 2, 4, GETDATE(), NULL),
('Sobremesa 4', 'Descripción 4', 930.00, 'Sobremesas', '/images/informatica/sobremesas/sobremesa_4.jpg', 30, 2, 4, GETDATE(), NULL),
('Sobremesa 5', 'Descripción 5', 870.00, 'Sobremesas', '/images/informatica/sobremesas/sobremesa_5.jpg', 30, 2, 4, GETDATE(), NULL),
('Sobremesa 6', 'Descripción 6', 870.00, 'Sobremesas', '/images/informatica/sobremesas/sobremesa_6.jpg', 30, 2, 4, GETDATE(), NULL),
('Sobremesa 7', 'Descripción 7', 930.00, 'Sobremesas', '/images/informatica/sobremesas/sobremesa_7.jpg', 30, 2, 4, GETDATE(), NULL),
('Sobremesa 8', 'Descripción 8', 930.00, 'Sobremesas', '/images/informatica/sobremesas/sobremesa_8.jpg', 30, 2, 4, GETDATE(), NULL),
('Sobremesa 9', 'Descripción 9', 930.00, 'Sobremesas', '/images/informatica/sobremesas/sobremesa_9.jpg', 30, 2, 4, GETDATE(), NULL),
('Sobremesa 10', 'Descripción 10', 870.00, 'Sobremesas', '/images/informatica/sobremesas/sobremesa_10.jpg', 30, 2, 4, GETDATE(), NULL),
('Sobremesa 11', 'Descripción 11', 870.00, 'Sobremesas', '/images/informatica/sobremesas/sobremesa_11.jpg', 30, 2, 4, GETDATE(), NULL),
('Software 1', 'Descripción 1', 160.00, 'Software', '/images/informatica/software/software_1.jpg', 30, 2, 4, GETDATE(), NULL),
('Software 2', 'Descripción 2', 160.00, 'Software', '/images/informatica/software/software_2.jpg', 30, 2, 4, GETDATE(), NULL),
('Software 3', 'Descripción 3', 160.00, 'Software', '/images/informatica/software/software_3.jpg', 30, 2, 4, GETDATE(), NULL),
('Software 4', 'Descripción 4', 160.00, 'Software', '/images/informatica/software/software_4.jpg', 30, 2, 4, GETDATE(), NULL),
('Software 5', 'Descripción 5', 160.00, 'Software', '/images/informatica/software/software_5.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 1', 'Descripción 1', 190.00, 'Tablets', '/images/informatica/tablets/tablet_1.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 2', 'Descripción 2', 190.00, 'Tablets', '/images/informatica/tablets/tablet_2.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 3', 'Descripción 3', 190.00, 'Tablets', '/images/informatica/tablets/tablet_3.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 4', 'Descripción 4', 170.00, 'Tablets', '/images/informatica/tablets/tablet_4.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 5', 'Descripción 5', 190.00, 'Tablets', '/images/informatica/tablets/tablet_5.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 6', 'Descripción 6', 190.00, 'Tablets', '/images/informatica/tablets/tablet_6.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 7', 'Descripción 7', 150.00, 'Tablets', '/images/informatica/tablets/tablet_7.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 8', 'Descripción 8', 190.00, 'Tablets', '/images/informatica/tablets/tablet_8.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 9', 'Descripción 9', 130.00, 'Tablets', '/images/informatica/tablets/tablet_9.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 10', 'Descripción 10', 190.00, 'Tablets', '/images/informatica/tablets/tablet_10.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 11', 'Descripción 11', 150.00, 'Tablets', '/images/informatica/tablets/tablet_11.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 12', 'Descripción 12', 190.00, 'Tablets', '/images/informatica/tablets/tablet_12.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 13', 'Descripción 13', 140.00, 'Tablets', '/images/informatica/tablets/tablet_13.jpg', 30, 2, 4, GETDATE(), NULL),
('Tablet 14', 'Descripción 14', 120.00, 'Tablets', '/images/informatica/tablets/tablet_14.jpg', 30, 2, 4, GETDATE(), NULL),
('Gafas de Sol Retro', 'Montura grande y elegante.', 24.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_1.jpg', 30, 2, 1, GETDATE(), NULL),
('Pendientes de Aro Dorado', 'Clásicos y ligeros.', 16.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_2.jpg', 30, 2, 1, GETDATE(), NULL),
('Cinturón Trenzado', 'Cuero sintético con hebilla redonda.', 16.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_3.jpg', 30, 2, 1, GETDATE(), NULL),
('Pañuelo Estampado', 'Multiusos para cuello o bolso.', 16.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_4.jpg', 30, 2, 1, GETDATE(), NULL),
('Pulsera Minimalista', 'Con cuentas doradas.', 24.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_5.jpg', 30, 2, 1, GETDATE(), NULL),
('Anillo con Piedra', 'Estilo boho con piedra turquesa.', 24.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_6.jpg', 30, 2, 1, GETDATE(), NULL),
('Diadema Acolchada', 'Color pastel, perfecta para verano.', 16.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_7.jpg', 30, 2, 1, GETDATE(), NULL),
('Sombrero de Playa', 'Ala ancha, protección solar.', 16.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_8.jpg', 30, 2, 1, GETDATE(), NULL),
('Collar de Capas', 'Tres cadenas doradas combinadas.', 24.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_9.jpg', 30, 2, 1, GETDATE(), NULL),
('Monedero Compacto', 'Práctico y moderno.', 16.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_10.jpg', 30, 2, 1, GETDATE(), NULL),
('Pulsera de Cuero', 'Estilo artesanal.', 24.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_11.jpg', 30, 2, 1, GETDATE(), NULL),
('Broche Floral', 'Detalle elegante para blusas o vestidos.', 16.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_12.jpg', 30, 2, 1, GETDATE(), NULL),
('Calcetines de Encaje', 'Perfectos para zapatos bajos.', 24.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_13.jpg', 30, 2, 1, GETDATE(), NULL),
('Guantes de Invierno', 'Suaves, con forro interior.', 16.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_14.jpg', 30, 2, 1, GETDATE(), NULL),
('Llavero Pompon', 'Colorido y decorativo para mochilas.', 24.00, 'Acesorios', '/images/ropa_hombre/acesorios/acesorio_15.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa de Lino Blanca', 'Fresca y elegante, ideal para verano.', 30.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_1.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa de Cuadros Rojos', 'Clásico estilo leñador.', 40.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_2.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa Oxford Azul Claro', 'Formal e informal a la vez.', 20.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_3.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa Slim Fit Negra', 'Para ocasiones especiales.', 20.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_4.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa Manga Corta Estampada', 'Ideal para clima cálido.', 30.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_5.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa Denim Azul Oscuro', 'Estilo vaquero moderno.', 40.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_6.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa a Rayas Verticales', 'Alarga visualmente el torso.', 40.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_7.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa con Cuello Mao', 'Elegante y diferente.', 30.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_8.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa con Bordado Sutil', 'Toque artesanal.', 20.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_9.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa Estilo Cubano', 'Cuello ancho, estilo retro.', 40.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_10.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa Negra Satinada', 'Ideal para salir de noche.', 30.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_11.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa Beige con Botones Madera', 'Estilo natural y bohemio.', 40.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_12.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa Blanca con Dobladillo Curvo', 'Detalle moderno.', 40.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_13.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa Azul Marino con Micropuntos', 'Elegancia discreta.', 40.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_14.jpg', 30, 2, 1, GETDATE(), NULL),
('Camisa Estilo Safari Kaki', 'Con bolsillos grandes.', 30.00, 'Camisas', '/images/ropa_hombre/camisas/camisa_15.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta Básica Blanca', 'Camiseta de algodón orgánico, cuello redondo.', 20.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_1.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta Estampada Urbana', 'Camiseta de corte amplio, muy cómoda para el día a día.', 30.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_2.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta Oversize Negra', 'Diseño fresco y veraniego con flores tropicales.', 20.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_3.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta a Rayas Azul', '“Libre y Feliz” impreso en el pecho.', 20.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_4.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta con Bolsillo Frontal', 'Perfecta para combinar con jeans de tiro alto.', 20.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_5.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta Tie-Dye Verde', 'Efecto tie dye en tonos pastel.', 30.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_6.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta con Cuello en V', 'Estilo náutico, en blanco y azul marino.', 20.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_7.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta de Manga Larga Negra', 'Detalles brillantes en el cuello y mangas.', 30.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_8.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta Deportiva Transpirable', 'Ideal para verano, tela fresca.', 20.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_9.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta Polo Azul Marino', 'Tejido elástico, perfecta para entretiempo.', 30.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_10.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta Eco-friendly Beige', 'Detalles de encaje en la parte superior.', 20.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_11.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta con Frase Divertida', 'Colores tierra y diseño relajado.', 30.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_12.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta Henley Verde Oliva', 'Bolsillo decorativo con lentejuelas.', 20.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_13.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta Retro 90s', 'Estilo varsity con rayas en mangas.', 20.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_14.jpg', 30, 2, 1, GETDATE(), NULL),
('Camiseta sin Mangas Negra', 'Estampa de los años 80 retro.', 30.00, 'Camisetas', '/images/ropa_hombre/camiseta/camiseta_15.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila de Cuero', 'Estilo urbano y resistente.', 52.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_1.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila Antirrobo Gris', 'Moderna y pequeña, ideal para salidas.', 78.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_2.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila de Cuero Marrón', 'Para uso diario.', 52.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_3.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila Deportiva Azul', 'Diseño alegre y juvenil.', 78.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_4.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila Compacta Plegable', 'Espalda acolchada y bolsillos extra.', 52.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_5.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila Vintage Tela', 'Se transforma en bolso.', 78.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_6.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila con USB Incorporado', 'Estilo rocker.', 52.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_7.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila para Portátil 15”', 'Estampados étnicos.', 52.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_8.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila Impermeable Verde Militar', 'Ideal para lluvia.', 52.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_9.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila Urbana con Cierres Metálicos', 'Detalles elegantes.', 52.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_10.jpg', 30, 2, 1, GETDATE(), NULL), 
('Mochila Eco de Tela Reciclada', 'Ideal para estudiantes.', 78.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_11.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila Escolar Multibolsillos', 'Estilo retro.', 78.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_12.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila Estilo Montañero', 'Tacto suave y elegante.', 78.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_13.jpg', 30, 2, 1, GETDATE(), NULL),
('Mochila Roll-top Negra', 'Tejido vaquero resistente.', 52.00, 'Mochilas', '/images/ropa_hombre/mochilas/mochilas_14.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón Chino Beige', 'Pierna ancha, muy cómodos.', 25.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_1.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón Vaquero Slim Azul', 'Bolsillos laterales, estilo urbano.', 30.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_2.jpg', 30, 2, 1, GETDATE(), NULL),
('Joggers Gris Claro', 'Corte ajustado, clásico.', 25.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_3.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón Cargo Verde Oliva', 'Ideal para verano.', 25.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_4.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón de Vestir Negro', 'Realza la figura.', 30.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_5.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón de Lino Blanco', 'Perfecto para hacer ejercicio.', 25.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_6.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón Jogger con Cierre', 'Diseño alegre para días soleados.', 25.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_7.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón Jeans Desgastado', 'Largo a media pierna, moderno.', 30.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_8.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón Corto Azul Marino', 'Look atrevido y de noche.', 25.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_9.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón Estilo Pijama Algodón', 'Denim de alta calidad.', 25.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_10.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón con Pinzas Gris', 'Ajustado en cintura, suelto en pierna.', 30.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_11.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón de Cuero Sintético Negro', 'Estilo formal para oficina.', 25.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_12.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón Recto Beige Claro', 'Cómodo y con estilo.', 25.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_13.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón Slim Fit Azul Oscuro', 'Estilo original y colorido.', 25.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_14.jpg', 30, 2, 1, GETDATE(), NULL),
('Pantalón de Felpa con Cintura Elástica', 'Cremalleras y cinturón.', 30.00, 'Pantalones', '/images/ropa_hombre/pantalones/pantalones_15.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera con Capucha Gris', 'Básica y cómoda.', 35.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_1.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera Oversize Rosa', 'Estilo relajado con puños ajustados.', 40.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_2.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera con Mensaje', '“Empowered Woman” en el pecho.', 35.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_3.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera Tie Dye', 'Tonos pastel, muy trendy.', 40.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_4.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera con Cierre', 'Cremallera frontal, ideal para entretiempo.', 40.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_5.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera Corta Crop', 'Perfecta para estilo casual.', 35.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_6.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera de Felpa', 'Interior suave, extra cálida.', 35.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_7.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera con Estampado Animal', 'Estilo urbano.', 40.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_8.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera Blanca Básica', 'Infaltable en el armario.', 35.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_9.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera con Bolsillos Laterales', 'Práctica y versátil.', 40.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_10.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera con Brillos', 'Detalles sutiles para brillar.', 35.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_11.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera Estilo Deportivo', 'Rayas en mangas.', 40.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_12.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera Bicolor', 'Combinación moderna de tonos neutros.', 35.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_13.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera con Orejitas', 'Detalle en la capucha, juvenil.', 35.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_14.jpg', 30, 2, 1, GETDATE(), NULL),
('Sudadera con Cuello Alto', 'Estilo más sofisticado.', 40.00, 'Sudaderas', '/images/ropa_hombre/sudaderas/sudadera_15.jpg', 30, 2, 1, GETDATE(), NULL),
('Zapatillas Blancas Urbanas', 'Estilo casual, suela cómoda.', 65.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_1.jpg', 30, 2, 1, GETDATE(), NULL),
('Zapatos de Vestir Negros', 'Tacón medio, perfectos para otoño.', 75.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_2.jpg', 30, 2, 1, GETDATE(), NULL),
('Botines de Cuero Marrón', 'Correas trenzadas, estilo veraniego.', 306500, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_3.jpg', 30, 2, 1, GETDATE(), NULL),
('Sandalias Deportivas Negras', 'Elegantes y neutros para toda ocasión.', 75.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_4.jpg', 30, 2, 1, GETDATE(), NULL),
('Mocasines Azul Marino', 'Ligeras y cómodas.', 75.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_5.jpg', 30, 2, 1, GETDATE(), NULL),
('Zapatillas Running Grises', 'Añaden altura sin incomodidad.', 75.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_6.jpg', 30, 2, 1, GETDATE(), NULL),
('Zapatos Náuticos Marrones', 'Estilo formal y brillante.', 75.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_7.jpg', 30, 2, 1, GETDATE(), NULL),
('Botas de Montaña Negras', 'Inspiradas en los 90s.', 75.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_8.jpg', 30, 2, 1, GETDATE(), NULL),
('Alpargatas Lino Beige', 'Estilo ecuestre.', 65.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_9.jpg', 30, 2, 1, GETDATE(), NULL),
('Zapatillas Chunky Negras', 'Hechas en España.', 75.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_10.jpg', 30, 2, 1, GETDATE(), NULL),
('Zapatos Brogue Cuero Natural', 'Estilo vintage.', 75.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_11.jpg', 30, 2, 1, GETDATE(), NULL),
('Zapatillas Skate Blancas', 'Brillantes y llamativos.', 65.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_12.jpg', 30, 2, 1, GETDATE(), NULL),
('Botas Chelsea Marrón Claro', 'Básicos para diario.', 75.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_13.jpg', 30, 2, 1, GETDATE(), NULL),
('Zapatos Oxford Vino', 'Sin talón, elegantes.', 65.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_14.jpg', 30, 2, 1, GETDATE(), NULL),
('Sandalias de Cuero Artesanales', 'Estilo salvaje y único.', 65.00, 'Zapatos', '/images/ropa_hombre/zapatos/zapatos_15.jpg', 30, 2, 1, GETDATE(), NULL),
('Llavero Pompon', 'Colorido y decorativo para mochilas.', 23.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_1.jpg', 30, 2, 2, GETDATE(), NULL),
('Pendientes de Aro Dorado', 'Clásicos y ligeros.', 12.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_2.jpg', 30, 2, 2, GETDATE(), NULL),
('Cinturón Trenzado', 'Cuero sintético con hebilla redonda.', 23.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_3.jpg', 30, 2, 2, GETDATE(), NULL),
('Pañuelo Estampado', 'Multiusos para cuello o bolso.', 12.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_4.jpg', 30, 2, 2, GETDATE(), NULL),
('Pulsera Minimalista', 'Con cuentas doradas.', 23.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_5.jpg', 30, 2, 2, GETDATE(), NULL),
('Anillo con Piedra', 'Estilo boho con piedra turquesa.', 12.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_6.jpg', 30, 2, 2, GETDATE(), NULL),
('Diadema Acolchada', 'Color pastel, perfecta para verano.', 23.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_7.jpg', 30, 2, 2, GETDATE(), NULL),
('Sombrero de Playa', 'Ala ancha, protección solar.', 23.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_8.jpg', 30, 2, 2, GETDATE(), NULL),
('Collar de Capas', 'Tres cadenas doradas combinadas.', 12.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_9.jpg', 30, 2, 2, GETDATE(), NULL),
('Monedero Compacto', 'Práctico y moderno.', 23.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_10.jpg', 30, 2, 2, GETDATE(), NULL),
('Pulsera de Cuero', 'Estilo artesanal.', 12.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_11.jpg', 30, 2, 2, GETDATE(), NULL),
('Broche Floral', 'Detalle elegante para blusas o vestidos.', 23.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_12.jpg', 30, 2, 2, GETDATE(), NULL),
('Calcetines de Encaje', 'Perfectos para zapatos bajos.', 12.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_13.jpg', 30, 2, 2, GETDATE(), NULL),
('Guantes de Invierno', 'Suaves, con forro interior.', 23.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_14.jpg', 30, 2, 2, GETDATE(), NULL),
('Llavero Pompon', 'Colorido y decorativo para mochilas.', 23.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_15.jpg', 30, 2, 2, GETDATE(), NULL),
('Llavero Pompon', 'Colorido y decorativo para mochilas.', 23.00, 'Acesorios', '/images/ropa_mujer/acesorios/acesorio_16.jpg', 30, 2, 2, GETDATE(), NULL),
('Gafas de Sol Retro', 'Montura grande y elegante.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_1.jpg', 30, 2, 2, GETDATE(), NULL),
('Pendientes de Aro Dorado', 'Clásicos y ligeros.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_2.jpg', 30, 2, 2, GETDATE(), NULL),
('Cinturón Trenzado', 'Cuero sintético con hebilla redonda.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_3.jpg', 30, 2, 2, GETDATE(), NULL),
('Pañuelo Estampado', 'Multiusos para cuello o bolso.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_4.jpg', 30, 2, 2, GETDATE(), NULL),
('Pulsera Minimalista', 'Con cuentas doradas.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_5.jpg', 30, 2, 2, GETDATE(), NULL),
('Anillo con Piedra', 'Estilo boho con piedra turquesa.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_6.jpg', 30, 2, 2, GETDATE(), NULL),
('Diadema Acolchada', 'Color pastel, perfecta para verano.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_7.jpg', 30, 2, 2, GETDATE(), NULL),
('Sombrero de Playa', 'Ala ancha, protección solar.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_8.jpg', 30, 2, 2, GETDATE(), NULL),
('Sombrero de Playa', 'Tres cadenas doradas combinadas.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_9.jpg', 30, 2, 2, GETDATE(), NULL),
('Monedero Compacto', 'Práctico y moderno.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_10.jpg', 30, 2, 2, GETDATE(), NULL),
('Pulsera de Cuero', 'Estilo artesanal.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_11.jpg', 30, 2, 2, GETDATE(), NULL),
('Broche Floral', 'Detalle elegante para blusas o vestidos.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_12.jpg', 30, 2, 2, GETDATE(), NULL),
('Calcetines de Encaje', 'Perfectos para zapatos bajos.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_13.jpg', 30, 2, 2, GETDATE(), NULL),
('Guantes de Invierno', 'Suaves, con forro interior.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_14.jpg', 30, 2, 2, GETDATE(), NULL),
('Llavero Pompon', 'Colorido y decorativo para mochilas.', 30.00, 'Blusas', '/images/ropa_mujer/blusas/blusa_15.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa de Lino Blanca', 'Fresca y elegante, ideal para verano.', 35.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_1.jpg', 30, 2, 2, GETDATE(), 20),
('Camisa de Cuadros Rojos', 'Clásico estilo leñador.', 40.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_2.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa Oxford Azul Claro', 'Formal e informal a la vez.', 35.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_3.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa Slim Fit Negra', 'Para ocasiones especiales.', 35.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_4.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa Manga Corta Estampada', 'Ideal para clima cálido.', 40.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_5.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa Denim Azul Oscuro', 'Estilo vaquero moderno.', 40.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_6.jpg', 30, 2, 2, GETDATE(), 50),
('Camisa a Rayas Verticales', 'Alarga visualmente el torso.', 35.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_7.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa con Cuello Mao', 'Elegante y diferente.', 40.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_8.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa con Bordado Sutil', 'Toque artesanal.', 35.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_9.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa Estilo Cubano', 'Cuello ancho, estilo retro.', 40.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_10.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa Negra Satinada', 'Ideal para salir de noche.', 40.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_11.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa Beige con Botones Madera', 'Estilo natural y bohemio.', 35.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_12.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa Blanca con Dobladillo Curvo', 'Detalle moderno.', 40.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_13.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa Azul Marino con Micropuntos', 'Elegancia discreta.', 35.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_14.jpg', 30, 2, 2, GETDATE(), NULL),
('Camisa Estilo Safari Kaki', 'Con bolsillos grandes.', 35.00, 'Camisas', '/images/ropa_mujer/camisas/camisa_15.jpg', 30, 2, 2, GETDATE(), 30),
('Camiseta Básica Blanca', 'Camiseta de algodón orgánico, cuello redondo.', 25.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_1.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta Estampada Urbana', 'Camiseta de corte amplio, muy cómoda para el día a día.', 15.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_2.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta Oversize Negra', 'Diseño fresco y veraniego con flores tropicales.', 25.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_3.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta a Rayas Azul', '“Libre y Feliz” impreso en el pecho.', 15.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_4.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta con Bolsillo Frontal', 'Perfecta para combinar con jeans de tiro alto.', 15.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_5.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta Tie-Dye Verde', 'Efecto tie dye en tonos pastel.', 25.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_6.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta con Cuello en V', 'Estilo náutico, en blanco y azul marino.', 15.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_7.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta de Manga Larga Negra', 'Detalles brillantes en el cuello y mangas.', 15.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_8.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta Deportiva Transpirable', 'Ideal para verano, tela fresca.', 25.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_9.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta Polo Azul Marino', 'Tejido elástico, perfecta para entretiempo.', 15.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_10.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta Eco-friendly Beige', 'Detalles de encaje en la parte superior.', 15.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_11.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta con Frase Divertida', 'Colores tierra y diseño relajado.', 25.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_12.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta Henley Verde Oliva', 'Bolsillo decorativo con lentejuelas.', 15.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_13.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta Retro 90s', 'Estilo varsity con rayas en mangas.', 15.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_14.jpg', 30, 2, 2, GETDATE(), NULL),
('Camiseta sin Mangas Negra', 'Estampa de los años 80 retro.', 15.00, 'Camisetas', '/images/ropa_mujer/camiseta/camiseta_15.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila Casual Negra', 'Estilo urbano y resistente.', 59.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_1.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila Antirrobo Gris', 'Moderna y pequeña, ideal para salidas.', 45.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_2.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila de Cuero Marrón', 'Para uso diario.', 59.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_3.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila Deportiva Azul', 'Diseño alegre y juvenil.', 45.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_4.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila Compacta Plegable', 'Espalda acolchada y bolsillos extra.', 59.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_5.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila Vintage Tela', 'Se transforma en bolso.', 45.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_6.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila con USB Incorporado', 'Estilo rocker.', 59.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_7.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila para Portátil 15”', 'Estampados étnicos.', 45.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_8.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila Impermeable Verde Militar', 'Ideal para lluvia.', 59.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_9.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila Urbana con Cierres Metálicos', 'Detalles elegantes.', 59.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_10.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila Eco de Tela Reciclada', 'Ideal para estudiantes.', 45.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_11.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila Escolar Multibolsillos', 'Estilo retro.', 59.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_12.jpg', 30, 2, 2, GETDATE(), 10),
('Mochila Estilo Montañero', 'Tacto suave y elegante.', 45.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_13.jpg', 30, 2, 2, GETDATE(), NULL),
('Mochila Roll-top Negra', 'Tejido vaquero resistente.', 59.00, 'Mochilas', '/images/ropa_mujer/mochilas/mochilas_14.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón Chino Beige', 'Pierna ancha, muy cómodos.', 15.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_1.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón Vaquero Slim Azul', 'Bolsillos laterales, estilo urbano.', 19.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_2.jpg', 30, 2, 2, GETDATE(), NULL),
('Joggers Gris Claro', 'Corte ajustado, clásico.', 19.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_3.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón Cargo Verde Oliva', 'Ideal para verano.', 19.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_4.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón de Vestir Negro', 'Realza la figura.', 19.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_5.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón de Lino Blanco', 'Perfecto para hacer ejercicio.', 15.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_6.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón Jogger con Cierre', 'Diseño alegre para días soleados.', 19.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_7.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón Jeans Desgastado', 'Largo a media pierna, moderno.', 15.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_8.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón Corto Azul Marino', 'Look atrevido y de noche.', 15.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_9.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón Estilo Pijama Algodón', 'Denim de alta calidad.', 15.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_10.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón con Pinzas Gris', 'Ajustado en cintura, suelto en pierna.', 19.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_11.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón de Cuero Sintético Negro', 'Estilo formal para oficina.', 15.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_12.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón Recto Beige Claro', 'Cómodo y con estilo.', 19.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_13.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón Slim Fit Azul Oscuro', 'Estilo original y colorido.', 19.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_14.jpg', 30, 2, 2, GETDATE(), NULL),
('Pantalón de Felpa con Cintura Elástica', 'Cremalleras y cinturón.', 15.00, 'Pantalones', '/images/ropa_mujer/pantalones/pantalones_15.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera con Capucha Gris', 'Básica y cómoda.', 65.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_1.jpg', 30, 2, 2, GETDATE(), 10),
('Sudadera Oversize Rosa', 'Estilo relajado con puños ajustados.', 70.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_2.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera con Mensaje', '“Empowered Woman” en el pecho.', 65.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_3.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera Tie Dye', 'Tonos pastel, muy trendy.', 65.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_4.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera con Cierre', 'Cremallera frontal, ideal para entretiempo.', 65.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_5.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera Corta Crop', 'Perfecta para estilo casual.', 65.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_6.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera de Felpa', 'Interior suave, extra cálida.', 70.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_7.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera con Estampado Animal', 'Estilo urbano.', 70.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_8.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera Blanca Básica', 'Infaltable en el armario.', 70.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_9.jpg', 30, 2, 2, GETDATE(), 5),
('Sudadera con Bolsillos Laterales', 'Práctica y versátil.', 65.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_10.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera con Brillos', 'Detalles sutiles para brillar.', 70.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_11.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera Estilo Deportivo', 'Rayas en mangas.', 65.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_12.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera Bicolor', 'Combinación moderna de tonos neutros.', 70.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_13.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera con Orejitas', 'Detalle en la capucha, juvenil.', 65.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_14.jpg', 30, 2, 2, GETDATE(), NULL),
('Sudadera con Cuello Alto', 'Estilo más sofisticado.', 65.00, 'Sudaderas', '/images/ropa_mujer/sudaderas/sudadera_15.jpg', 30, 2, 2, GETDATE(), NULL),
('Zapatillas Blancas Urbanas', 'Estilo casual, suela cómoda.', 99.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_1.jpg', 30, 2, 2, GETDATE(), NULL),
('Zapatos de Vestir Negros', 'Tacón medio, perfectos para otoño.', 110.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_2.jpg', 30, 2, 2, GETDATE(), NULL),
('Botines de Cuero Marrón', 'Correas trenzadas, estilo veraniego.', 110.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_3.jpg', 30, 2, 2, GETDATE(), NULL),
('Sandalias Deportivas Negras', 'Elegantes y neutros para toda ocasión.', 99.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_4.jpg', 30, 2, 2, GETDATE(), NULL),
('Mocasines Azul Marino', 'Ligeras y cómodas.', 110.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_5.jpg', 30, 2, 2, GETDATE(), NULL),
('Zapatillas Running Grises', 'Añaden altura sin incomodidad.', 99.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_6.jpg', 30, 2, 2, GETDATE(), NULL),
('Zapatos Náuticos Marrones', 'Estilo formal y brillante.', 110.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_7.jpg', 30, 2, 2, GETDATE(), 15),
('Botas de Montaña Negras', 'Inspiradas en los 90s.', 99.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_8.jpg', 30, 2, 2, GETDATE(), NULL),
('Alpargatas Lino Beige', 'Estilo ecuestre.', 110.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_9.jpg', 30, 2, 2, GETDATE(), NULL),
('Zapatillas Chunky Negras', 'Hechas en España.', 110.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_10.jpg', 30, 2, 2, GETDATE(), NULL),
('Zapatos Brogue Cuero Natural', 'Estilo vintage.', 99.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_11.jpg', 30, 2, 2, GETDATE(), NULL),
('Zapatillas Skate Blancas', 'Brillantes y llamativos.', 99.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_12.jpg', 30, 2, 2, GETDATE(), NULL),
('Botas Chelsea Marrón Claro', 'Básicos para diario.', 99.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_13.jpg', 30, 2, 2, GETDATE(), NULL),
('Zapatos Oxford Vino', 'Sin talón, elegantes.', 99.00, 'Zapatos', '/images/ropa_mujer/zapatos/zapatos_14.jpg', 30, 2, 2, GETDATE(), NULL),
('Juguetes 1', 'Descripción 1', 20.00, 'Juguetes', '/images/kids_toys/juguetes/juguetes_1.jpg', 30, 2, 5, GETDATE(), NULL),
('Juguetes 2', 'Descripción 2', 30.00, 'Juguetes', '/images/kids_toys/juguetes/juguetes_2.jpg', 30, 2, 5, GETDATE(), NULL),
('Juguetes 3', 'Descripción 3', 05.00, 'Juguetes', '/images/kids_toys/juguetes/juguetes_3.jpg', 30, 2, 5, GETDATE(), NULL),
('Juguetes 4', 'Descripción 4', 10.00, 'Juguetes', '/images/kids_toys/juguetes/juguetes_4.jpg', 30, 2, 5, GETDATE(), NULL),
('Juguetes 5', 'Descripción 5', 05.00, 'Juguetes', '/images/kids_toys/juguetes/juguetes_5.jpg', 30, 2, 5, GETDATE(), NULL),
('Juegos 1', 'Descripción 1', 15.00, 'Juegos', '/images/kids_toys/juegos/juegos_1.jpg', 30, 2, 5, GETDATE(), NULL),
('Juegos 2', 'Descripción 2', 20.00, 'Juegos', '/images/kids_toys/juegos/juegos_2.jpg', 30, 2, 5, GETDATE(), 50),
('Juegos 3', 'Descripción 3', 19.00, 'Juegos', '/images/kids_toys/juegos/juegos_3.jpg', 30, 2, 5, GETDATE(), NULL),
('Juegos 4', 'Descripción 4', 30.00, 'Juegos', '/images/kids_toys/juegos/juegos_4.jpg', 30, 2, 5, GETDATE(), NULL),
('Juegos 5', 'Descripción 5', 30.00, 'Juegos', '/images/kids_toys/juegos/juegos_5.jpg', 30, 2, 5, GETDATE(), NULL),
('Bebé 1', 'Descripción 1', 25.00, 'Bebé', '/images/kids_toys/bebe/bebe_1.jpg', 30, 2, 5, GETDATE(), NULL),
('Bebé 2', 'Descripción 2', 20.00, 'Bebé', '/images/kids_toys/bebe/bebe_2.jpg', 30, 2, 5, GETDATE(), NULL),
('Bebé 3', 'Descripción 3', 25.00, 'Bebé', '/images/kids_toys/bebe/bebe_3.jpg', 30, 2, 5, GETDATE(), 30),
('Bebé 4', 'Descripción 4', 20.00, 'Bebé', '/images/kids_toys/bebe/bebe_4.jpg', 30, 2, 5, GETDATE(), NULL),
('Bebé 5', 'Descripción 5', 25.00, 'Bebé', '/images/kids_toys/bebe/bebe_5.jpg', 30, 2, 5, GETDATE(), NULL),
('Ropa de Bebé 1', 'Descripción 1', 25.00, 'Ropa de Bebé', '/images/kids_toys/ropa_bebe/ropabebe_1.jpg', 30, 2, 5, GETDATE(), NULL),
('Ropa de Bebé 2', 'Descripción 2', 25.00, 'Ropa de Bebé', '/images/kids_toys/ropa_bebe/ropabebe_2.jpg', 30, 2, 5, GETDATE(), 10),
('Ropa de Bebé 3', 'Descripción 3', 20.00, 'Ropa de Bebé', '/images/kids_toys/ropa_bebe/ropabebe_3.jpg', 30, 2, 5, GETDATE(), NULL),
('Ropa de Bebé 4', 'Descripción 4', 30.00, 'Ropa de Bebé', '/images/kids_toys/ropa_bebe/ropabebe_4.jpg', 30, 2, 5, GETDATE(), NULL),
('Ropa de Bebé 5', 'Descripción 5', 20.00, 'Ropa de Bebé', '/images/kids_toys/ropa_bebe/ropabebe_5.jpg', 30, 2, 5, GETDATE(), NULL),
('Materias de Oficina 1', 'Descripción 1', 40.00, 'Materias de Oficina', '/images/oficina/materias_oficina/materiasoficina_1.jpg', 30, 2, 6, GETDATE(), NULL),
('Materias de Oficina 2', 'Descripción 2', 30.00, 'Materias de Oficina', '/images/oficina/materias_oficina/materiasoficina_2.jpg', 30, 2, 6, GETDATE(), NULL),
('Materias de Oficina 3', 'Descripción 3', 40.00, 'Materias de Oficina', '/images/oficina/materias_oficina/materiasoficina_3.jpg', 30, 2, 6, GETDATE(), NULL),
('Materias de Oficina 4', 'Descripción 4', 30.00, 'Materias de Oficina', '/images/oficina/materias_oficina/materiasoficina_4.jpg', 30, 2, 6, GETDATE(), NULL),
('Materias de Oficina 5', 'Descripción 5', 40.00, 'Materias de Oficina', '/images/oficina/materias_oficina/materiasoficina_5.jpg', 30, 2, 6, GETDATE(), NULL),
('Papel 1', 'Descripción 1', 10.00, 'Papel', '/images/oficina/papel/papel_1.jpg', 30, 2, 6, GETDATE(), NULL),
('Papel 2', 'Descripción 2', 10.00, 'Papel', '/images/oficina/papel/papel_2.jpg', 30, 2, 6, GETDATE(), NULL),
('Papel 3', 'Descripción 3', 10.00, 'Papel', '/images/oficina/papel/papel_3.jpg', 30, 2, 6, GETDATE(), NULL),
('Papel 4', 'Descripción 4', 10.00, 'Papel', '/images/oficina/papel/papel_4.jpg', 30, 2, 6, GETDATE(), 15),
('Papel 5', 'Descripción 5', 10.00, 'Papel', '/images/oficina/papel/papel_5.jpg', 30, 2, 6, GETDATE(), NULL),
('Bolígrafos 1', 'Descripción 1', 05.00, 'Bolígrafos', '/images/oficina/boligrafos/boligrafos_1.jpg', 30, 2, 6, GETDATE(), NULL),
('Bolígrafos 2', 'Descripción 2', 05.00, 'Bolígrafos', '/images/oficina/boligrafos/boligrafos_2.jpg', 30, 2, 6, GETDATE(), NULL),
('Bolígrafos 3', 'Descripción 3', 05.00, 'Bolígrafos', '/images/oficina/boligrafos/boligrafos_3.jpg', 30, 2, 6, GETDATE(), 35),
('Bolígrafos 4', 'Descripción 4', 05.00, 'Bolígrafos', '/images/oficina/boligrafos/boligrafos_4.jpg', 30, 2, 6, GETDATE(), NULL),
('Bolígrafos 5', 'Descripción 5', 05.00, 'Bolígrafos', '/images/oficina/boligrafos/boligrafos_5.jpg', 30, 2, 6, GETDATE(), NULL),
('Impreso 1', 'Descripción 1', 05.00, 'Impreso', '/images/oficina/impreso/impreso_1.jpg', 30, 2, 6, GETDATE(), 20),
('Impreso 2', 'Descripción 2', 05.00, 'Impreso', '/images/oficina/impreso/impreso_2.jpg', 30, 2, 6, GETDATE(), NULL),
('Impreso 3', 'Descripción 3', 05.00, 'Impreso', '/images/oficina/impreso/impreso_3.jpg', 30, 2, 6, GETDATE(), NULL),
('Impreso 4', 'Descripción 4', 05.00, 'Impreso', '/images/oficina/impreso/impreso_4.jpg', 30, 2, 6, GETDATE(), NULL),
('Impreso 5', 'Descripción 5', 05.00, 'Impreso', '/images/oficina/impreso/impreso_5.jpg', 30, 2, 6, GETDATE(), NULL),
('Tinta 1', 'Descripción 1', 12.00, 'Tinta', '/images/oficina/tinta/tinta_1.jpg', 30, 2, 6, GETDATE(), NULL),
('Tinta 2', 'Descripción 2', 14.00, 'Tinta', '/images/oficina/tinta/tinta_2.jpg', 30, 2, 6, GETDATE(), NULL),
('Tinta 3', 'Descripción 3', 12.00, 'Tinta', '/images/oficina/tinta/tinta_3.jpg', 30, 2, 6, GETDATE(), NULL),
('Tinta 4', 'Descripción 4', 14.00, 'Tinta', '/images/oficina/tinta/tinta_4.jpg', 30, 2, 6, GETDATE(), NULL),
('Tinta 5', 'Descripción 5', 12.00, 'Tinta', '/images/oficina/tinta/tinta_5.jpg', 30, 2, 6, GETDATE(), NULL),
('Mochila Casual Negra', 'Descripción 1', 30.00, 'Mochilas', '/images/oficina/mochilas/mochilas_1.jpg', 30, 2, 6, GETDATE(), NULL),
('Mochila Antirrobo Gris', 'Descripción 2', 30.00, 'Mochilas', '/images/oficina/mochilas/mochilas_2.jpg', 30, 2, 6, GETDATE(), NULL),
('Mochila de Cuero Marrón', 'Descripción 3', 30.00, 'Mochilas', '/images/oficina/mochilas/mochilas_3.jpg', 30, 2, 6, GETDATE(), NULL),
('Mochila Deportiva Azul', 'Descripción 4', 30.00, 'Mochilas', '/images/oficina/mochilas/mochilas_4.jpg', 30, 2, 6, GETDATE(), 15),
('Mochila Compacta Plegable', 'Descripción 5', 30.00, 'Mochilas', '/images/oficina/mochilas/mochilas_5.jpg', 30, 2, 6, GETDATE(), NULL),
('Cocina 1', 'Descripción 1', 45.00, 'Cocina', '/images/hogar/cocina/cocina_1.jpg', 30, 2, 7, GETDATE(), NULL),
('Cocina 2', 'Descripción 2', 55.00, 'Cocina', '/images/hogar/cocina/cocina_2.jpg', 30, 2, 7, GETDATE(), NULL),
('Cocina 3', 'Descripción 3', 45.00, 'Cocina', '/images/hogar/cocina/cocina_3.jpg', 30, 2, 7, GETDATE(), NULL),
('Cocina 4', 'Descripción 4', 55.00, 'Cocina', '/images/hogar/cocina/cocina_4.jpg', 30, 2, 7, GETDATE(), NULL),
('Cocina 5', 'Descripción 5', 55.00, 'Cocina', '/images/hogar/cocina/cocina_5.jpg', 30, 2, 7, GETDATE(), NULL),
('Comedor 1', 'Descripción 1', 35.00, 'Comedor', '/images/hogar/comedor/comedor_1.jpg', 30, 2, 7, GETDATE(), NULL),
('Comedor 2', 'Descripción 2', 39.00, 'Comedor', '/images/hogar/comedor/comedor_2.jpg', 30, 2, 7, GETDATE(), NULL),
('Comedor 3', 'Descripción 3', 35.00, 'Comedor', '/images/hogar/comedor/comedor_3.jpg', 30, 2, 7, GETDATE(), NULL),
('Comedor 4', 'Descripción 4', 39.00, 'Comedor', '/images/hogar/comedor/comedor_4.jpg', 30, 2, 7, GETDATE(), NULL),
('Comedor 5', 'Descripción 5', 39.00, 'Comedor', '/images/hogar/comedor/comedor_5.jpg', 30, 2, 7, GETDATE(), NULL),
('Dormitorio 1', 'Descripción 1', 45.00, 'Dormitorio', '/images/hogar/dormitorio/dormitorio_1.jpg', 30, 2, 7, GETDATE(), NULL),
('Dormitorio 2', 'Descripción 2', 45.00, 'Dormitorio', '/images/hogar/dormitorio/dormitorio_2.jpg', 30, 2, 7, GETDATE(), NULL),
('Dormitorio 3', 'Descripción 3', 37.00, 'Dormitorio', '/images/hogar/dormitorio/dormitorio_3.jpg', 30, 2, 7, GETDATE(), NULL),
('Dormitorio 4', 'Descripción 4', 37.00, 'Dormitorio', '/images/hogar/dormitorio/dormitorio_4.jpg', 30, 2, 7, GETDATE(), NULL),
('Dormitorio 5', 'Descripción 5', 45.00, 'Dormitorio', '/images/hogar/dormitorio/dormitorio_5.jpg', 30, 2, 7, GETDATE(), NULL),
('Salón 1', 'Descripción 1', 80.00, 'Salón', '/images/hogar/salon/salon_1.jpg', 30, 2, 7, GETDATE(), NULL),
('Salón 2', 'Descripción 2', 77.00, 'Salón', '/images/hogar/salon/salon_2.jpg', 30, 2, 7, GETDATE(), NULL),
('Salón 3', 'Descripción 3', 80.00, 'Salón', '/images/hogar/salon/salon_3.jpg', 30, 2, 7, GETDATE(), NULL),
('Salón 4', 'Descripción 4', 98.00, 'Salón', '/images/hogar/salon/salon_4.jpg', 30, 2, 7, GETDATE(), NULL),
('Salón 5', 'Descripción 5', 100.00, 'Salón', '/images/hogar/salon/salon_5.jpg', 30, 2, 7, GETDATE(), 50),
('Baño 1', 'Descripción 1', 40.00, 'Baño', '/images/hogar/bano/bano_1.jpg', 30, 2, 7, GETDATE(), NULL),
('Baño 2', 'Descripción 2', 67.00, 'Baño', '/images/hogar/bano/bano_2.jpg', 30, 2, 7, GETDATE(), NULL),
('Baño 3', 'Descripción 3', 67.00, 'Baño', '/images/hogar/bano/bano_3.jpg', 30, 2, 7, GETDATE(), NULL),
('Baño 4', 'Descripción 4', 67.00, 'Baño', '/images/hogar/bano/bano_4.jpg', 30, 2, 7, GETDATE(), NULL),
('Baño 5', 'Descripción 5', 30.00, 'Baño', '/images/hogar/bano/bano_5.jpg', 30, 2, 7, GETDATE(), NULL),
('Jardín 1', 'Descripción 1', 87.00, 'Jardín', '/images/hogar/jardin/jardin_1.jpg', 30, 2, 7, GETDATE(), NULL),
('Jardín 2', 'Descripción 2', 65.00, 'Jardín', '/images/hogar/jardin/jardin_2.jpg', 30, 2, 7, GETDATE(), 25),
('Jardín 3', 'Descripción 3', 87.00, 'Jardín', '/images/hogar/jardin/jardin_3.jpg', 30, 2, 7, GETDATE(), NULL),
('Jardín 4', 'Descripción 4', 65.00, 'Jardín', '/images/hogar/jardin/jardin_4.jpg', 30, 2, 7, GETDATE(), NULL),
('Jardín 5', 'Descripción 5', 87.00, 'Jardín', '/images/hogar/jardin/jardin_5.jpg', 30, 2, 7, GETDATE(), NULL),
('Iluminación 1', 'Descripción 1', 120.00, 'Iluminación', '/images/hogar/iluminacion/iluminacion_1.jpg', 30, 2, 7, GETDATE(), NULL),
('Iluminación 2', 'Descripción 2', 120.00, 'Iluminación', '/images/hogar/iluminacion/iluminacion_2.jpg', 30, 2, 7, GETDATE(), NULL),
('Iluminación 3', 'Descripción 3', 125.00, 'Iluminación', '/images/hogar/iluminacion/iluminacion_3.jpg', 30, 2, 7, GETDATE(), NULL),
('Iluminación 4', 'Descripción 4', 130.00, 'Iluminación', '/images/hogar/iluminacion/iluminacion_4.jpg', 30, 2, 7, GETDATE(), 30),
('Iluminación 5', 'Descripción 5', 130.00, 'Iluminación', '/images/hogar/iluminacion/iluminacion_5.jpg', 30, 2, 7, GETDATE(), NULL),
('pequeños electrodomésticos 1', 'Descripción 1', 30.00, 'pequeños electrodomésticos', '/images/hogar/pequenos_electrodomesticos/electrop_1.jpg', 30, 2, 7, GETDATE(), NULL),
('pequeños electrodomésticos 2', 'Descripción 2', 40.00, 'pequeños electrodomésticos', '/images/hogar/pequenos_electrodomesticos/electrop_2.jpg', 30, 2, 7, GETDATE(), NULL),
('pequeños electrodomésticos 3', 'Descripción 3', 67.00, 'pequeños electrodomésticos', '/images/hogar/pequenos_electrodomesticos/electrop_3.jpg', 30, 2, 7, GETDATE(), 30),
('pequeños electrodomésticos 4', 'Descripción 4', 56.00, 'pequeños electrodomésticos', '/images/hogar/pequenos_electrodomesticos/electrop_4.jpg', 30, 2, 7, GETDATE(), NULL),
('pequeños electrodomésticos 5', 'Descripción 5', 45.00, 'pequeños electrodomésticos', '/images/hogar/pequenos_electrodomesticos/electrop_5.jpg', 30, 2, 7, GETDATE(), NULL),
('grandes electrodomésticos 1', 'Descripción 1', 267.00, 'grandes electrodomésticos', '/images/hogar/grandes_electrodomesticos/electrog_1.jpg', 30, 2, 7, GETDATE(), NULL),
('grandes electrodomésticos 2', 'Descripción 2', 445.00, 'grandes electrodomésticos', '/images/hogar/grandes_electrodomesticos/electrog_2.jpg', 30, 2, 7, GETDATE(), 50),
('grandes electrodomésticos 3', 'Descripción 3', 330.00, 'grandes electrodomésticos', '/images/hogar/grandes_electrodomesticos/electrog_3.jpg', 30, 2, 7, GETDATE(), NULL),
('grandes electrodomésticos 4', 'Descripción 4', 130.00, 'grandes electrodomésticos', '/images/hogar/grandes_electrodomesticos/electrog_4.jpg', 30, 2, 7, GETDATE(), NULL),
('grandes electrodomésticos 5', 'Descripción 5', 690.00, 'grandes electrodomésticos', '/images/hogar/grandes_electrodomesticos/electrog_5.jpg', 30, 2, 7, GETDATE(), NULL),
('Ficción 1', 'Descripción 1', 40.00, 'Ficción', '/images/libros/ficcion/ficcion_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Ficción 2', 'Descripción 2', 80.00, 'Ficción', '/images/libros/ficcion/ficcion_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Ficción 3', 'Descripción 3', 40.00, 'Ficción', '/images/libros/ficcion/ficcion_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Ficción 4', 'Descripción 4', 80.00, 'Ficción', '/images/libros/ficcion/ficcion_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Ficción 5', 'Descripción 5', 80.00, 'Ficción', '/images/libros/ficcion/ficcion_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Consulta 1', 'Descripción 1', 30.00, 'Consulta', '/images/libros/consulta/consulta_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Consulta 2', 'Descripción 2', 30.00, 'Consulta', '/images/libros/consulta/consulta_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Consulta 3', 'Descripción 3', 30.00, 'Consulta', '/images/libros/consulta/consulta_3.jpg', 30, 2, 8, GETDATE(), 20),
('Consulta 4', 'Descripción 4', 30.00, 'Consulta', '/images/libros/consulta/consulta_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Consulta 5', 'Descripción 5', 30.00, 'Consulta', '/images/libros/consulta/consulta_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Arte 1', 'Descripción 1', 40.00, 'Arte', '/images/libros/arte/arte_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Arte 2', 'Descripción 2', 50.00, 'Arte', '/images/libros/arte/arte_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Arte 3', 'Descripción 3', 40.00, 'Arte', '/images/libros/arte/arte_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Arte 4', 'Descripción 4', 50.00, 'Arte', '/images/libros/arte/arte_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Arte 5', 'Descripción 5', 40.00, 'Arte', '/images/libros/arte/arte_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Fotografía 1', 'Descripción 1', 15.00, 'Fotografía', '/images/libros/fotografia/fotografia_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Fotografía 2', 'Descripción 2', 15.00, 'Fotografía', '/images/libros/fotografia/fotografia_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Fotografía 3', 'Descripción 3', 15.00, 'Fotografía', '/images/libros/fotografia/fotografia_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Fotografía 4', 'Descripción 4', 15.00, 'Fotografía', '/images/libros/fotografia/fotografia_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Fotografía 5', 'Descripción 5', 15.00, 'Fotografía', '/images/libros/fotografia/fotografia_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Historia 1', 'Descripción 1', 15.00, 'Historia', '/images/libros/historia/historia_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Historia 2', 'Descripción 2', 12.00, 'Historia', '/images/libros/historia/historia_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Historia 3', 'Descripción 3', 15.00, 'Historia', '/images/libros/historia/historia_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Historia 4', 'Descripción 4', 10.00, 'Historia', '/images/libros/historia/historia_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Historia 5', 'Descripción 5', 10.00, 'Historia', '/images/libros/historia/historia_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Humor 1', 'Descripción 1', 20.00, 'Humor', '/images/libros/humor/humor_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Humor 2', 'Descripción 2', 20.00, 'Humor', '/images/libros/humor/humor_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Humor 3', 'Descripción 3', 20.00, 'Humor', '/images/libros/humor/humor_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Humor 4', 'Descripción 4', 20.00, 'Humor', '/images/libros/humor/humor_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Humor 5', 'Descripción 5', 20.00, 'Humor', '/images/libros/humor/humor_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Infantil 1', 'Descripción 1', 10.00, 'Infantil', '/images/libros/infantil/infantil_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Infantil 2', 'Descripción 2', 15.00, 'Infantil', '/images/libros/infantil/infantil_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Infantil 3', 'Descripción 3', 15.00, 'Infantil', '/images/libros/infantil/infantil_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Infantil 4', 'Descripción 4', 10.00, 'Infantil', '/images/libros/infantil/infantil_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Infantil 5', 'Descripción 5', 15.00, 'Infantil', '/images/libros/infantil/infantil_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Ciencias 1', 'Descripción 1', 10.00, 'Ciencias', '/images/libros/ciencias/ciencias_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Ciencias 2', 'Descripción 2', 10.00, 'Ciencias', '/images/libros/ciencias/ciencias_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Ciencias 3', 'Descripción 3', 10.00, 'Ciencias', '/images/libros/ciencias/ciencias_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Ciencias 4', 'Descripción 4', 10.00, 'Ciencias', '/images/libros/ciencias/ciencias_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Ciencias 5', 'Descripción 5', 15.00, 'Ciencias', '/images/libros/ciencias/ciencias_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Medicina 1', 'Descripción 1', 10.00, 'Medicina', '/images/libros/medicina/medicina_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Medicina 2', 'Descripción 2', 15.00, 'Medicina', '/images/libros/medicina/medicina_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Medicina 3', 'Descripción 3', 10.00, 'Medicina', '/images/libros/medicina/medicina_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Medicina 4', 'Descripción 4', 10.00, 'Medicina', '/images/libros/medicina/medicina_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Medicina 5', 'Descripción 5', 15.00, 'Medicina', '/images/libros/medicina/medicina_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Comics y Manga 1', 'Descripción 1', 17.00, 'Comics y Manga', '/images/libros/comics_manga/comicsmanga_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Comics y Manga 2', 'Descripción 2', 17.00, 'Comics y Manga', '/images/libros/comics_manga/comicsmanga_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Comics y Manga 3', 'Descripción 3', 17.00, 'Comics y Manga', '/images/libros/comics_manga/comicsmanga_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Comics y Manga 4', 'Descripción 4', 17.00, 'Comics y Manga', '/images/libros/comics_manga/comicsmanga_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Comics y Manga 5', 'Descripción 5', 17.00, 'Comics y Manga', '/images/libros/comics_manga/comicsmanga_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Deportes 1', 'Descripción 1', 55.00, 'Deportes', '/images/libros/deportes/deportes_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Deportes 2', 'Descripción 2', 55.00, 'Deportes', '/images/libros/deportes/deportes_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Deportes 3', 'Descripción 3', 55.00, 'Deportes', '/images/libros/deportes/deportes_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Deportes 4', 'Descripción 4', 55.00, 'Deportes', '/images/libros/deportes/deportes_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Deportes 5', 'Descripción 5', 55.00, 'Deportes', '/images/libros/deportes/deportes_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Derecho 1', 'Descripción 1', 80.00, 'Derecho', '/images/libros/derecho/derecho_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Derecho 2', 'Descripción 2', 80.00, 'Derecho', '/images/libros/derecho/derecho_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Derecho 3', 'Descripción 3', 80.00, 'Derecho', '/images/libros/derecho/derecho_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Derecho 4', 'Descripción 4', 80.00, 'Derecho', '/images/libros/derecho/derecho_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Derecho 5', 'Descripción 5', 80.00, 'Derecho', '/images/libros/derecho/derecho_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Economía 1', 'Descripción 1', 80.00, 'Economía', '/images/libros/economia/economia_1.jpg', 30, 2, 8, GETDATE(), NULL),
('Economía 2', 'Descripción 2', 80.00, 'Economía', '/images/libros/economia/economia_2.jpg', 30, 2, 8, GETDATE(), NULL),
('Economía 3', 'Descripción 3', 80.00, 'Economía', '/images/libros/economia/economia_3.jpg', 30, 2, 8, GETDATE(), NULL),
('Economía 4', 'Descripción 4', 80.00, 'Economía', '/images/libros/economia/economia_4.jpg', 30, 2, 8, GETDATE(), NULL),
('Economía 5', 'Descripción 5', 80.00, 'Economía', '/images/libros/economia/economia_5.jpg', 30, 2, 8, GETDATE(), NULL),
('Xbox Series X y Y 1', 'Descripción 1', 550.00, 'Xbox Series X y Y', '/images/videojuegos/xbox/xbox_1.jpg', 30, 2, 9, GETDATE(), NULL),
('Xbox Series X y Y 2', 'Descripción 2', 550.00, 'Xbox Series X y Y', '/images/videojuegos/xbox/xbox_2.jpg', 30, 2, 9, GETDATE(), NULL),
('Xbox Series X y Y 3', 'Descripción 3', 550.00, 'Xbox Series X y Y', '/images/videojuegos/xbox/xbox_3.jpg', 30, 2, 9, GETDATE(), NULL),
('Xbox Series X y Y 4', 'Descripción 4', 550.00, 'Xbox Series X y Y', '/images/videojuegos/xbox/xbox_4.jpg', 30, 2, 9, GETDATE(), NULL),
('Xbox Series X y Y 5', 'Descripción 5', 550.00, 'Xbox Series X y Y', '/images/videojuegos/xbox/xbox_5.jpg', 30, 2, 9, GETDATE(), NULL),
('Playstation 5 y 4 1', 'Descripción 1', 550.00, 'Playstation 5 y 4', '/images/videojuegos/playstation/playstation_1.jpg', 30, 2, 9, GETDATE(), NULL),
('Playstation 5 y 4 2', 'Descripción 2', 550.00, 'Playstation 5 y 4', '/images/videojuegos/playstation/playstation_2.jpg', 30, 2, 9, GETDATE(), NULL),
('Playstation 5 y 4 3', 'Descripción 3', 550.00, 'Playstation 5 y 4', '/images/videojuegos/playstation/playstation_3.jpg', 30, 2, 9, GETDATE(), NULL),
('Playstation 5 y 4 4', 'Descripción 4', 550.00, 'Playstation 5 y 4', '/images/videojuegos/playstation/playstation_4.jpg', 30, 2, 9, GETDATE(), NULL),
('Playstation 5 y 4 5', 'Descripción 5', 550.00, 'Playstation 5 y 4', '/images/videojuegos/playstation/playstation_5.jpg', 30, 2, 9, GETDATE(), NULL),
('Nintendo Switch 1', 'Descripción 1', 300.00, 'Nintendo Switch', '/images/videojuegos/nintendo/nintendo_1.jpg', 30, 2, 9, GETDATE(), NULL),
('Nintendo Switch 2', 'Descripción 2', 300.00, 'Nintendo Switch', '/images/videojuegos/nintendo/nintendo_2.jpg', 30, 2, 9, GETDATE(), NULL),
('Nintendo Switch 3', 'Descripción 3', 300.00, 'Nintendo Switch', '/images/videojuegos/nintendo/nintendo_3.jpg', 30, 2, 9, GETDATE(), NULL),
('Nintendo Switch 4', 'Descripción 4', 300.00, 'Nintendo Switch', '/images/videojuegos/nintendo/nintendo_4.jpg', 30, 2, 9, GETDATE(), NULL),
('Nintendo Switch 5', 'Descripción 5', 300.00, 'Nintendo Switch', '/images/videojuegos/nintendo/nintendo_5.jpg', 30, 2, 9, GETDATE(), NULL),
('Realidad Virtual 1', 'Descripción 1', 430.00, 'Realidad Virtual', '/images/videojuegos/vr/vr_1.jpg', 30, 2, 9, GETDATE(), NULL),
('Realidad Virtual 2', 'Descripción 2', 430.00, 'Realidad Virtual', '/images/videojuegos/vr/vr_2.jpg', 30, 2, 9, GETDATE(), NULL),
('Realidad Virtual 3', 'Descripción 3', 430.00, 'Realidad Virtual', '/images/videojuegos/vr/vr_3.jpg', 30, 2, 9, GETDATE(), NULL),
('Realidad Virtual 4', 'Descripción 4', 430.00, 'Realidad Virtual', '/images/videojuegos/vr/vr_4.jpg', 30, 2, 9, GETDATE(), NULL),
('Realidad Virtual 5', 'Descripción 5', 430.00, 'Realidad Virtual', '/images/videojuegos/vr/vr_5.jpg', 30, 2, 9, GETDATE(), 35);
